attractor_decoder_dropout: 0.1
attractor_encoder_dropout: 0.1
attractor_loss_ratio: 2.0
context_size: 7
ekld_loss_weight: 1.0e-06
encoder_units: 2048
estimate_spk_qty: 2
estimate_spk_qty_thr: -1
feature_dim: 80
frame_shift: 160
frame_size: 400
gpu: 0
hidden_size: 256
input_transform: logmel_meannorm
median_window_length: 15
model_type: TransformerEDA
num_esamples: 1
num_frames: -1
num_zsamples: 1
sampling_rate: 16000
seed: 3
subsampling: 10
temp: 1.0
threshold: 0.45
time_shuffle: true
transformer_encoder_dropout: 0.1
transformer_encoder_n_heads: 4
transformer_encoder_n_layers: 4
use_mu_e: false
use_mu_z: false
vad_loss_weight: 1.0
zkld_loss_weight: 1.0e-06
